server:
  port: 8080

# MySQL configuration
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/online_judge
    username: root
    password:

# Language config
language-config:
  languages:
    - language: java
      fileExtension: .java
      compileCommand: cd ${sourceFileDirectory} && javac ${submissionId}.java
      runCommand: cd ${sourceFileDirectory} && java ${submissionId} < ${inputFilePath} > ${outputFilePath}
    - language: cpp
      fileExtension: .cpp
      compileCommand: cd ${sourceFileDirectory} && g++ -std=c++11 ${submissionId}.cpp -o ${problemCode}.out
      runCommand: cd ${sourceFileDirectory} && ./${submissionId}.out < ${inputFilePath} > ${outputFilePath}
    - language: python
      fileExtension: .py
      compileCommand:
      runCommand: cd ${sourceFileDirectory} && python3 ${submissionId}.py < ${inputFilePath} > ${outputFilePath}